version: "3.1"
# Uses in authnet
#
# WHAT DOES THIS MEAN? The server profiles used in this example are intended for use with edge versions of the product image only.

services:
  pingfederate:
    image: pingidentity/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    command: wait-for pingdirectory:389 -t 900 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/webshield-dev/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingfederate
      - PING_IDENTITY_ACCEPT_EULA=YES
      - VERBOSE=false
    env_file:
      # Configuration file created when setup.sh (Getting-started project root directory) is first run to source
      # devops user/key details for evaluation licenses and for docker image/git tags
      - ~/.pingidentity/devops
    # Example: Examples below for mounting local directories for inbound server profile and persisting
    #          server build.  The local /opt/out directory must be empty when building new server
    #             /opt/out - Resulting server build
    #             /opt/in  - Inbound server-profile detail in liue of SERVER_PROFILE_URL (must be commented out)
    #volumes:
    #   - ${HOME}/projects/devops/volumes/simple-sync.pingfederate:/opt/out
    #   - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    volumes:
       - ./opt1/out:/opt/out
       - ./opt1/in:/opt/in
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet

  pingdirectory:
    image: pingidentity/pingdirectory:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingdirectory
      - PING_IDENTITY_ACCEPT_EULA=YES
    env_file:
      - ~/.pingidentity/devops
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    #volumes:
    #   - ${HOME}/projects/devops/volumes/simple-sync.pingdirectory:/opt/out
    #   - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in

    ports:
      - 1636:636
      - 1443:443
      - 1389:389
    networks:
      - pingnet

networks:
    pingnet:
